[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
build_src_filter =
  +<firmware/src/**>
build_flags =
  -std=c++17
  -I firmware/include
test_build_src = yes

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -std=c++17
  -I firmware/include
lib_deps =
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/Adafruit ADS1X15
