[wokwi]
version = 1
firmware = 'wokwi/ci/.pio/build/esp32-c3-devkitm-1/firmware.bin'
elf = 'wokwi/ci/.pio/build/esp32-c3-devkitm-1/firmware.elf'
vcdFile = 'wokwi/ci/artifacts/wokwi.vcd'

[serial]
port = 4000
