[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/Adafruit ADS1X15
build_flags =
  -std=c++17
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_MODE=0
